### ISSUE TITLE
how to use/start it?

### ISSUE THREAD

**Issue by onthetunnel** [magicalne/show-me-your-money#1]
Hello , can i know how to install and run it on ubuntu 18.0.4 , can you teach me please .. Thanks You!

**Comment by magicalne** [comment]
Sorry for the delay. I have not been working on this project for now.
This is a prototype for triangle arbitrage of cryptocurrency. I tried binance and huobi.
Unfortunately, there is little space for arbitrage. For binance, liquidity is so good due to great API and low latency(they use aws in Japan). For huobi, worst API and unpredictable latency.

It's too risky.
